language: go
sudo: false
go_import_path: cert-check

go:
  - 1.6.x
  - 1.7.x
  - master

install:
  - go get ./...
  - go build

before_script:
  - go vet ./...

script:
  - go test ./...
  - ./cert-check -d -v -e 1
  - ./cert-check -d -e 10000
